### ISSUE TITLE
5c9061 throws error (Cannot read property 'forEach' of undefined)

### ISSUE THREAD

**Issue by JAAlperin** [thomasloven/lovelace-card-modder#8]
Running 83.3 on 141.  Updated card-modder last night to 5c9061.  Got error below.  Tried 5c9061d this morning.  Same error.  Had to go back to b44fb3.

Log Details (ERROR)
Thu Dec 13 2018 10:22:10 GMT-0500 (Eastern Standard Time)

https://xxxxxx.duckdns.org/frontend_latest/app-0fd67575.js:89:305 Uncaught TypeError: Cannot read property 'forEach' of undefined

Log Details (ERROR)
Thu Dec 13 2018 10:23:10 GMT-0500 (Eastern Standard Time)

https://xxxxxx.duckdns.org/local/custom_ui/lovelace/card-modder/card-modder.js?v=5c9061:45:20 Uncaught TypeError: Cannot read property 'forEach' of undefined

Thank you for your excellent contributions to Home Assistant.

Jeff Alperin.

**Comment by JAAlperin** [comment]
Very sorry, Thomas, but one of the two views in which I use card-modder is still throwing an error.  Works with b44fb3 (as previously reported).

Log Details (ERROR)
Thu Dec 13 2018 17:04:03 GMT-0500 (Eastern Standard Time)

https://hass.sacl.duckdns.org/local/custom_ui/lovelace/card-modder/card-modder.js?v=069956:52:25 Uncaught TypeError: Cannot read property 'report_size' of undefined

Jeff

**Comment by thomasloven** [comment]
That should be fixed now, but I'm afraid that card probably isn't configured correctly...

**Comment by JAAlperin** [comment]
Again I am sorry to report that I still have the error:
Log Details (ERROR)
Thu Dec 13 2018 22:15:23 GMT-0500 (Eastern Standard Time)

https://xxxxxx.duckdns.org/local/custom_ui/lovelace/card-modder/card-modder.js?v=6813b1:53:25 Uncaught TypeError: Cannot read property 'report_size' of undefined

Please consider:
* Two views contain exactly the same card (but with different id):
`    - id: view_sensors_card_entities_appliances
        type: custom:card-modder
        card:
           type: entities
           title: Appliance Sensors
           entities:
              - binary_sensor.coffee_pot_opened
        style:
           --paper-item-icon-active-color: red`
* The first view worked as of two fixes ago, but now the card does not show.  The second view fails with the error above.
* With b44fb3 both views show the card properly.

**Comment by thomasloven** [comment]
That's very odd...
Try 8b64cfd.

**Comment by JAAlperin** [comment]
Hi Thomas.

Went to try 8b64cfd, but found newer 35eb37.  Tried that.
First got "Can't find card-tools" in both views where the card-modder should have been.
Installed card-tools.  No errors, but card-modder cards disappeared from both views.
Back to b44fb3 for now.

Can I help in some way?

**Comment by thomasloven** [comment]
Does your browser log say anything?

**Comment by JAAlperin** [comment]
Yes, here is Chrome log.  Haven't tried another browser.

[xxxxxx.duckdns.org-1544790382453.log](https://github.com/thomasloven/lovelace-card-modder/files/2680044/xxxxxx.duckdns.org-1544790382453.log)

**Comment by thomasloven** [comment]
If you open up the chrome console (ctrl + shift + J) in your lovelace view and type `window.cardTools` what does it say?

**Comment by thomasloven** [comment]
Wait!
I should have realized. Card-modder requires Home Assistant 0.48...

Unfortunately, upgrading to 0.48 will break custom-ui for you.

**Comment by JAAlperin** [comment]
I’m thoroughly confused now.  I’m running hassio 0.83.3 on hassio supervisor 141 on Docker CE on Raspbian.  Home Assistant 0.48 seems like ancient history.  What am I missing?

Anyway, card-modder does work (just b44fb3 not 35eb37).



Regards,

Jeff Alperin

H: 561-666-7789
C: 561-797-9876

"It's not rocket surgery!" - Oscar Leroy
"You know my rule about circus music!" - Lacey Burroughs

**Comment by JAAlperin** [comment]
Here is snippet from Chrome console.  I believe the same was part of the log file I previously uploaded.

11:48:34.826 card-modder.js?v=35eb37:20 Uncaught (in promise) TypeError: window.cardTools.litHtml is not a function
    at HTMLElement.render (card-modder.js?v=35eb37:20)
    at HTMLElement.update (ba7ed9f3515f27cc7b5a.chunk.js:169)
    at HTMLElement._validate (ba7ed9f3515f27cc7b5a.chunk.js:145)
    at HTMLElement._invalidate (ba7ed9f3515f27cc7b5a.chunk.js:145)

**Comment by thomasloven** [comment]
Sorry. I meant to say 0.84.

**Comment by thomasloven** [comment]
I took the liberty of removing your phone numbers from your message, by the way. I suspect you didn't really wish them published on the internet...
